/* Generated by runtime.cmake from PSXRECOMP_BIOS_STEMS — do not edit. */
#include "psx_bios_backend.h"

extern const PsxBiosBackend OpenBIOS_psx_bios_backend;

const PsxBiosBackend *const psx_bios_registry[] = {
    &OpenBIOS_psx_bios_backend,
};
const uint32_t psx_bios_registry_count = 1u;
