format_version = 2

[[package]]
id = "psx.enhancement.cd-speed"

[[package]]
id = "psx.enhancement.fast-loading"

[[feature]]
package_id = "psx.enhancement.cd-speed"
id = "cd-speed"
enabled = true

[[feature]]
package_id = "psx.enhancement.fast-loading"
id = "fast-loading"
enabled = true
